defaults: ../../grpo_math_1B.yaml
grpo:
  max_num_steps: 2
  num_prompts_per_step: 8
  num_generations_per_prompt: 4
  async_grpo:
    enabled: true
    in_flight_weight_updates: true
loss_fn:
  use_importance_sampling_correction: true
  force_on_policy_ratio: true
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-nemotron3.5-lightning-native-mxfp4-mxfp8
policy:
  model_name: nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16
  tokenizer:
    name: nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-NVFP4
  train_global_batch_size: 32
  train_micro_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 8192
  make_sequence_length_divisible_by: 16
  dtensor_cfg:
    enabled: false
  megatron_cfg:
    enabled: true
    expert_model_parallel_size: 8
    sequence_parallel: true
    activation_checkpointing: true
    moe_router_dtype: fp32
    moe_router_enable_expert_bias: true
    moe_grouped_gemm: true
    use_fused_weighted_squared_relu: true
    bias_activation_fusion: false
    mtp_loss_scaling_factor: 0.3
    mtp_use_repeated_layer: true
    mtp_num_layers: 5
    mtp_detach_heads: true
    fp8_cfg:
      enabled: true
      fp8_recipe: mxfp8
      fp8_param: true
      mxfp4_moe_weight_native: true
    te_precision_config_file: /opt/nemo-rl/te_config.yaml
    optimizer:
      use_precision_aware_optimizer: false
    env_vars:
      NVTE_FP8_BLOCK_SCALING_FP32_SCALES: '1'
      PYTORCH_CUDA_ALLOC_CONF: expandable_segments:False
  sequence_packing:
    enabled: false
  generation:
    colocated:
      enabled: false
      resources:
        num_nodes: 2
        gpus_per_node: 4
    vllm_cfg:
      async_engine: true
      tensor_parallel_size: 2
      gpu_memory_utilization: 0.7
      precision: fp8
      is_mx: true
      refit_with_reload_api: true
      mxfp4_moe_weight_native: true
      quantization_ignore_patterns:
      - '*mtp*'
      - model.layers.*.self_attn.*
      - model.layers.*.linear_attn.*
      - model.layers.*.mlp.gate
      - model.layers.*.mlp.shared_expert*
      - lm_head
    vllm_kwargs:
      moe_backend: flashinfer_cutlass_afp8
data:
  max_input_seq_length: 2048
logger:
  log_dir: logs/grpo-nemotron3.5-lightning-native-mxfp4-mxfp8
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-nemotron3.5-lightning-native-mxfp4-mxfp8
cluster:
  gpus_per_node: 4
  num_nodes: 4
  segment_size: 2
