sft:
  max_num_epochs: 1
  max_num_steps: 10000
  val_period: 500
  val_batches: 4
  val_global_batch_size: 128
  val_micro_batch_size: 2
  val_at_start: false
  seed: 42
checkpointing:
  enabled: true
  checkpoint_dir: results/sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long
  metric_name: val_loss
  higher_is_better: false
  keep_top_k: 3
  save_period: 50
  checkpoint_must_save_by: null
policy:
  model_name: meta-llama/Llama-3.1-8B
  tokenizer:
    name: meta-llama/Llama-3.1-8B-Instruct
  train_global_batch_size: 512
  train_micro_batch_size: 2
  max_total_sequence_length: 4096
  precision: bfloat16
  dtensor_cfg:
    enabled: true
    cpu_offload: false
    sequence_parallel: false
    activation_checkpointing: false
    tensor_parallel_size: 4
    context_parallel_size: 1
    custom_parallel_plan: null
  dynamic_batching:
    enabled: true
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    sequence_length_round: 64
  sequence_packing:
    enabled: false
  make_sequence_length_divisible_by: 1
  max_grad_norm: 1
  optimizer:
    name: torch.optim.AdamW
    kwargs:
      lr: 2e-5
      weight_decay: 0.01
      betas:
        - 0.9
        - 0.98
      eps: 1e-08
      foreach: false
      fused: false
data:
  max_input_seq_length: ${policy.max_total_sequence_length}
  dataset_name: "openmathinstruct2"
  prompt_file: examples/prompts/math.txt
  split: "train_1M"
  add_bos: true
  add_eos: true
  add_generation_prompt: true
  output_key: 'generated_solution'
  seed: 42
  shuffle: true
logger:
  log_dir: logs/sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long
  wandb_enabled: true
  tensorboard_enabled: true
  mlflow_enabled: false
  monitor_gpus: true
  wandb:
    project: nemo-rl
    name: sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long
  tensorboard:
    log_dir: tb_logs-sft-dev-squad
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10
cluster:
  gpus_per_node: 8
  num_nodes: 1
