sft:
  max_num_epochs: 1
  max_num_steps: 350
  val_period: 500
  val_batches: 8
  val_global_batch_size: 32
  val_micro_batch_size: 1
  val_at_start: true
  seed: 42
checkpointing:
  enabled: true
  checkpoint_dir: results/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp
  metric_name: val_loss
  higher_is_better: false
  keep_top_k: 3
  save_period: 20
  checkpoint_must_save_by: null
policy:
  model_name: meta-llama/Llama-3.1-8B
  tokenizer:
    name: meta-llama/Llama-3.1-8B-Instruct
  train_global_batch_size: 512
  train_micro_batch_size: 2
  max_total_sequence_length: 4096
  precision: bfloat16
  dtensor_cfg:
    enabled: true
    cpu_offload: false
    sequence_parallel: true
    activation_checkpointing: false
    tensor_parallel_size: 2
    context_parallel_size: 1
    custom_parallel_plan: null
  dynamic_batching:
    enabled: false
  sequence_packing:
    enabled: false
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    algorithm: "modified_first_fit_decreasing"
    sequence_length_round: 64
  make_sequence_length_divisible_by: 2
  max_grad_norm: 1
  optimizer:
    name: torch.optim.AdamW
    kwargs:
      lr: 2e-5
      weight_decay: 0.01
      betas:
        - 0.9
        - 0.98
      eps: 1e-08
      foreach: false
      fused: false
data:
  max_input_seq_length: ${policy.max_total_sequence_length}
  dataset_name: "openmathinstruct2"
  prompt_file: examples/prompts/math.txt
  split: "train_1M"
  add_bos: true
  add_eos: true
  add_generation_prompt: true
  output_key: 'generated_solution'
  shuffle: true
  seed: 42
logger:
  log_dir: logs/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp
  wandb_enabled: true
  tensorboard_enabled: true
  mlflow_enabled: false
  monitor_gpus: true
  wandb:
    project: nemo-rl
    name: sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp
  tensorboard:
    log_dir: tb_logs-sft-dev-openmathinstruct2
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10
cluster:
  gpus_per_node: 8
  num_nodes: 1
