# GRPO Algorithm Configuration
defaults: "grpo_math_8B_megatron.yaml"

loss_fn:
  use_importance_sampling_correction: true

policy:
  generation:
    vllm_cfg:
      precision: 'fp8'
      use_deep_gemm: true
  megatron_cfg:
    tensor_model_parallel_size: 2
    fp8_cfg:
      enabled: true
      fp8: "hybrid"
      fp8_recipe: "blockwise"
      fp8_param: false